version = 1

test_patterns = [
    "*.spec.js",
    "*.spec.jsx",
    "*.spec.ts",
    "*.spec.tsx",
    "*.test.js",
    "*.test.jsx",
    "*.test.ts",
    "*.test.tsx",
]

exclude_patterns = [
    "__mocks__",
    "scripts",
    "dist",
    "build"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
